spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:banmanwa
    username: sa
    password:
  h2:
    console:
      enabled: true
security:
  jwt:
    secret-key: my_secret_is_secret
    tokenValid-time : 10800000